name: 24/7 WinGo Auto Run

on:
  schedule:
    - cron: '*/1 * * * *' # প্রতি ১ মিনিট পরপর চলবে
  workflow_dispatch:

jobs:
  run-signal:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Signal
        run: |
          curl -sL "https://bdtgame72-netizen.github.io/pro_predicson/"
