name: 24/7 WinGo Auto Signal

on:
  schedule:
    - cron: '*/1 * * * *' # প্রতি ১ মিনিট পরপর চলবে
  workflow_dispatch:

jobs:
  refresh-signal:
    runs-on: ubuntu-latest
    steps:
      - name: Open Signal Link
        run: |
          # এটি আপনার গিটহাব পেজটি সার্ভারে ওপেন করবে যা সিগন্যাল ট্রিগার করবে
          curl -sL "https://bdtgame72-netizen.github.io/pro_predicson/" > /dev/null
          echo "Signal Triggered Successfully"
